# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'customBoggle.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(600, 623)
        Form.setMinimumSize(QtCore.QSize(400, 500))
        Form.setMaximumSize(QtCore.QSize(600, 750))
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.radioButton = QtWidgets.QRadioButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton.sizePolicy().hasHeightForWidth())
        self.radioButton.setSizePolicy(sizePolicy)
        self.radioButton.setMinimumSize(QtCore.QSize(50, 30))
        self.radioButton.setMaximumSize(QtCore.QSize(100, 30))
        self.radioButton.setObjectName("radioButton")
        self.buttonGroup = QtWidgets.QButtonGroup(Form)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.radioButton)
        self.horizontalLayout.addWidget(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_2.sizePolicy().hasHeightForWidth())
        self.radioButton_2.setSizePolicy(sizePolicy)
        self.radioButton_2.setMinimumSize(QtCore.QSize(50, 30))
        self.radioButton_2.setMaximumSize(QtCore.QSize(100, 30))
        self.radioButton_2.setObjectName("radioButton_2")
        self.buttonGroup.addButton(self.radioButton_2)
        self.horizontalLayout.addWidget(self.radioButton_2)
        self.radioButton_3 = QtWidgets.QRadioButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_3.sizePolicy().hasHeightForWidth())
        self.radioButton_3.setSizePolicy(sizePolicy)
        self.radioButton_3.setMinimumSize(QtCore.QSize(50, 30))
        self.radioButton_3.setMaximumSize(QtCore.QSize(100, 30))
        self.radioButton_3.setObjectName("radioButton_3")
        self.buttonGroup.addButton(self.radioButton_3)
        self.horizontalLayout.addWidget(self.radioButton_3)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMinimumSize(QtCore.QSize(100, 30))
        self.pushButton.setMaximumSize(QtCore.QSize(200, 50))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setMinimumSize(QtCore.QSize(100, 30))
        self.pushButton_2.setMaximumSize(QtCore.QSize(200, 50))
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)
        
        self.setupLayout = QtWidgets.QGridLayout()
        self.setupLayout.setContentsMargins(0, 0, 0, 0)
        self.setupLayout.setSpacing(10)
        self.setupLayout.setObjectName("setupLayout")
        self.lineh3 = QtWidgets.QFrame(Form)
        self.lineh3.setFrameShape(QtWidgets.QFrame.HLine)
        self.lineh3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lineh3.setObjectName("lineh3")
        self.setupLayout.addWidget(self.lineh3, 8, 0, 1, 11)
        self.lineh1 = QtWidgets.QFrame(Form)
        self.lineh1.setFrameShape(QtWidgets.QFrame.HLine)
        self.lineh1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lineh1.setObjectName("lineh1")
        self.setupLayout.addWidget(self.lineh1, 4, 0, 1, 11)
        self.lineh4 = QtWidgets.QFrame(Form)
        self.lineh4.setFrameShape(QtWidgets.QFrame.HLine)
        self.lineh4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lineh4.setObjectName("lineh4")
        self.setupLayout.addWidget(self.lineh4, 10, 0, 1, 11)
        self.linev04 = QtWidgets.QFrame(Form)
        self.linev04.setFrameShape(QtWidgets.QFrame.VLine)
        self.linev04.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.linev04.setObjectName("linev04")
        self.setupLayout.addWidget(self.linev04, 1, 9, 1, 1)
        self.lineh0 = QtWidgets.QFrame(Form)
        self.lineh0.setFrameShape(QtWidgets.QFrame.HLine)
        self.lineh0.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lineh0.setObjectName("lineh0")
        self.setupLayout.addWidget(self.lineh0, 2, 0, 1, 11)
        self.linev21 = QtWidgets.QFrame(Form)
        self.linev21.setFrameShape(QtWidgets.QFrame.VLine)
        self.linev21.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.linev21.setObjectName("linev21")
        self.setupLayout.addWidget(self.linev21, 5, 3, 1, 1)
        self.linev34 = QtWidgets.QFrame(Form)
        self.linev34.setFrameShape(QtWidgets.QFrame.VLine)
        self.linev34.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.linev34.setObjectName("linev34")
        self.setupLayout.addWidget(self.linev34, 7, 9, 1, 1)
        self.linev11 = QtWidgets.QFrame(Form)
        self.linev11.setFrameShape(QtWidgets.QFrame.VLine)
        self.linev11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.linev11.setObjectName("linev11")
        self.setupLayout.addWidget(self.linev11, 3, 3, 1, 1)
        self.linev54 = QtWidgets.QFrame(Form)
        self.linev54.setFrameShape(QtWidgets.QFrame.VLine)
        self.linev54.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.linev54.setObjectName("linev54")
        self.setupLayout.addWidget(self.linev54, 11, 9, 1, 1)
        self.linev53 = QtWidgets.QFrame(Form)
        self.linev53.setFrameShape(QtWidgets.QFrame.VLine)
        self.linev53.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.linev53.setObjectName("linev53")
        self.setupLayout.addWidget(self.linev53, 11, 7, 1, 1)
        self.linev51 = QtWidgets.QFrame(Form)
        self.linev51.setFrameShape(QtWidgets.QFrame.VLine)
        self.linev51.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.linev51.setObjectName("linev51")
        self.setupLayout.addWidget(self.linev51, 11, 3, 1, 1)
        self.linev52 = QtWidgets.QFrame(Form)
        self.linev52.setFrameShape(QtWidgets.QFrame.VLine)
        self.linev52.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.linev52.setObjectName("linev52")
        self.setupLayout.addWidget(self.linev52, 11, 5, 1, 1)
        self.linev02 = QtWidgets.QFrame(Form)
        self.linev02.setFrameShape(QtWidgets.QFrame.VLine)
        self.linev02.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.linev02.setObjectName("linev02")
        self.setupLayout.addWidget(self.linev02, 1, 5, 1, 1)
        self.linev41 = QtWidgets.QFrame(Form)
        self.linev41.setFrameShape(QtWidgets.QFrame.VLine)
        self.linev41.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.linev41.setObjectName("linev41")
        self.setupLayout.addWidget(self.linev41, 9, 3, 1, 1)
        self.linev50 = QtWidgets.QFrame(Form)
        self.linev50.setFrameShape(QtWidgets.QFrame.VLine)
        self.linev50.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.linev50.setObjectName("linev50")
        self.setupLayout.addWidget(self.linev50, 11, 1, 1, 1)
        self.linev43 = QtWidgets.QFrame(Form)
        self.linev43.setFrameShape(QtWidgets.QFrame.VLine)
        self.linev43.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.linev43.setObjectName("linev43")
        self.setupLayout.addWidget(self.linev43, 9, 7, 1, 1)
        self.letter02 = QtWidgets.QComboBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.letter02.sizePolicy().hasHeightForWidth())
        self.letter02.setSizePolicy(sizePolicy)
        self.letter02.setMinimumSize(QtCore.QSize(50, 30))
        self.letter02.setObjectName("letter02")
        self.setupLayout.addWidget(self.letter02, 1, 4, 1, 1)
        self.letter05 = QtWidgets.QComboBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.letter05.sizePolicy().hasHeightForWidth())
        self.letter05.setSizePolicy(sizePolicy)
        self.letter05.setMinimumSize(QtCore.QSize(50, 30))
        self.letter05.setObjectName("letter05")
        self.setupLayout.addWidget(self.letter05, 1, 10, 1, 1)
        self.linev24 = QtWidgets.QFrame(Form)
        self.linev24.setFrameShape(QtWidgets.QFrame.VLine)
        self.linev24.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.linev24.setObjectName("linev24")
        self.setupLayout.addWidget(self.linev24, 5, 9, 1, 1)
        self.letter34 = QtWidgets.QComboBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.letter34.sizePolicy().hasHeightForWidth())
        self.letter34.setSizePolicy(sizePolicy)
        self.letter34.setMinimumSize(QtCore.QSize(50, 30))
        self.letter34.setObjectName("letter34")
        self.setupLayout.addWidget(self.letter34, 7, 8, 1, 1)
        self.linev10 = QtWidgets.QFrame(Form)
        self.linev10.setFrameShape(QtWidgets.QFrame.VLine)
        self.linev10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.linev10.setObjectName("linev10")
        self.setupLayout.addWidget(self.linev10, 3, 1, 1, 1)
        self.letter14 = QtWidgets.QComboBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.letter14.sizePolicy().hasHeightForWidth())
        self.letter14.setSizePolicy(sizePolicy)
        self.letter14.setMinimumSize(QtCore.QSize(50, 30))
        self.letter14.setObjectName("letter14")
        self.setupLayout.addWidget(self.letter14, 3, 8, 1, 1)
        self.linev40 = QtWidgets.QFrame(Form)
        self.linev40.setFrameShape(QtWidgets.QFrame.VLine)
        self.linev40.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.linev40.setObjectName("linev40")
        self.setupLayout.addWidget(self.linev40, 9, 1, 1, 1)
        self.linev00 = QtWidgets.QFrame(Form)
        self.linev00.setFrameShape(QtWidgets.QFrame.VLine)
        self.linev00.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.linev00.setObjectName("linev00")
        self.setupLayout.addWidget(self.linev00, 1, 1, 1, 1)
        self.linev03 = QtWidgets.QFrame(Form)
        self.linev03.setFrameShape(QtWidgets.QFrame.VLine)
        self.linev03.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.linev03.setObjectName("linev03")
        self.setupLayout.addWidget(self.linev03, 1, 7, 1, 1)
        self.linev20 = QtWidgets.QFrame(Form)
        self.linev20.setFrameShape(QtWidgets.QFrame.VLine)
        self.linev20.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.linev20.setObjectName("linev20")
        self.setupLayout.addWidget(self.linev20, 5, 1, 1, 1)
        self.linev01 = QtWidgets.QFrame(Form)
        self.linev01.setFrameShape(QtWidgets.QFrame.VLine)
        self.linev01.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.linev01.setObjectName("linev01")
        self.setupLayout.addWidget(self.linev01, 1, 3, 1, 1)
        self.linev12 = QtWidgets.QFrame(Form)
        self.linev12.setFrameShape(QtWidgets.QFrame.VLine)
        self.linev12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.linev12.setObjectName("linev12")
        self.setupLayout.addWidget(self.linev12, 3, 5, 1, 1)
        self.lineh2 = QtWidgets.QFrame(Form)
        self.lineh2.setFrameShape(QtWidgets.QFrame.HLine)
        self.lineh2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lineh2.setObjectName("lineh2")
        self.setupLayout.addWidget(self.lineh2, 6, 0, 1, 11)
        self.linev44 = QtWidgets.QFrame(Form)
        self.linev44.setFrameShape(QtWidgets.QFrame.VLine)
        self.linev44.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.linev44.setObjectName("linev44")
        self.setupLayout.addWidget(self.linev44, 9, 9, 1, 1)
        self.letter00 = QtWidgets.QComboBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.letter00.sizePolicy().hasHeightForWidth())
        self.letter00.setSizePolicy(sizePolicy)
        self.letter00.setMinimumSize(QtCore.QSize(50, 30))
        self.letter00.setObjectName("letter00")
        self.setupLayout.addWidget(self.letter00, 1, 0, 1, 1)
        self.linev31 = QtWidgets.QFrame(Form)
        self.linev31.setFrameShape(QtWidgets.QFrame.VLine)
        self.linev31.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.linev31.setObjectName("linev31")
        self.setupLayout.addWidget(self.linev31, 7, 3, 1, 1)
        self.linev14 = QtWidgets.QFrame(Form)
        self.linev14.setFrameShape(QtWidgets.QFrame.VLine)
        self.linev14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.linev14.setObjectName("linev14")
        self.setupLayout.addWidget(self.linev14, 3, 9, 1, 1)
        self.linev13 = QtWidgets.QFrame(Form)
        self.linev13.setFrameShape(QtWidgets.QFrame.VLine)
        self.linev13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.linev13.setObjectName("linev13")
        self.setupLayout.addWidget(self.linev13, 3, 7, 1, 1)
        self.linev23 = QtWidgets.QFrame(Form)
        self.linev23.setFrameShape(QtWidgets.QFrame.VLine)
        self.linev23.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.linev23.setObjectName("linev23")
        self.setupLayout.addWidget(self.linev23, 5, 7, 1, 1)
        self.linev30 = QtWidgets.QFrame(Form)
        self.linev30.setFrameShape(QtWidgets.QFrame.VLine)
        self.linev30.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.linev30.setObjectName("linev30")
        self.setupLayout.addWidget(self.linev30, 7, 1, 1, 1)
        self.linev33 = QtWidgets.QFrame(Form)
        self.linev33.setFrameShape(QtWidgets.QFrame.VLine)
        self.linev33.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.linev33.setObjectName("linev33")
        self.setupLayout.addWidget(self.linev33, 7, 7, 1, 1)
        self.linev22 = QtWidgets.QFrame(Form)
        self.linev22.setFrameShape(QtWidgets.QFrame.VLine)
        self.linev22.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.linev22.setObjectName("linev22")
        self.setupLayout.addWidget(self.linev22, 5, 5, 1, 1)
        self.linev42 = QtWidgets.QFrame(Form)
        self.linev42.setFrameShape(QtWidgets.QFrame.VLine)
        self.linev42.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.linev42.setObjectName("linev42")
        self.setupLayout.addWidget(self.linev42, 9, 5, 1, 1)
        self.linev32 = QtWidgets.QFrame(Form)
        self.linev32.setFrameShape(QtWidgets.QFrame.VLine)
        self.linev32.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.linev32.setObjectName("linev32")
        self.setupLayout.addWidget(self.linev32, 7, 5, 1, 1)
        self.letter53 = QtWidgets.QComboBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.letter53.sizePolicy().hasHeightForWidth())
        self.letter53.setSizePolicy(sizePolicy)
        self.letter53.setMinimumSize(QtCore.QSize(50, 30))
        self.letter53.setObjectName("letter53")
        self.setupLayout.addWidget(self.letter53, 11, 6, 1, 1)
        self.letter31 = QtWidgets.QComboBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.letter31.sizePolicy().hasHeightForWidth())
        self.letter31.setSizePolicy(sizePolicy)
        self.letter31.setMinimumSize(QtCore.QSize(50, 30))
        self.letter31.setObjectName("letter31")
        self.setupLayout.addWidget(self.letter31, 7, 2, 1, 1)
        self.letter45 = QtWidgets.QComboBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.letter45.sizePolicy().hasHeightForWidth())
        self.letter45.setSizePolicy(sizePolicy)
        self.letter45.setMinimumSize(QtCore.QSize(50, 30))
        self.letter45.setObjectName("letter45")
        self.setupLayout.addWidget(self.letter45, 9, 10, 1, 1)
        self.letter01 = QtWidgets.QComboBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.letter01.sizePolicy().hasHeightForWidth())
        self.letter01.setSizePolicy(sizePolicy)
        self.letter01.setMinimumSize(QtCore.QSize(50, 30))
        self.letter01.setObjectName("letter01")
        self.setupLayout.addWidget(self.letter01, 1, 2, 1, 1)
        self.letter20 = QtWidgets.QComboBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.letter20.sizePolicy().hasHeightForWidth())
        self.letter20.setSizePolicy(sizePolicy)
        self.letter20.setMinimumSize(QtCore.QSize(50, 30))
        self.letter20.setObjectName("letter20")
        self.setupLayout.addWidget(self.letter20, 5, 0, 1, 1)
        self.letter12 = QtWidgets.QComboBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.letter12.sizePolicy().hasHeightForWidth())
        self.letter12.setSizePolicy(sizePolicy)
        self.letter12.setMinimumSize(QtCore.QSize(50, 30))
        self.letter12.setObjectName("letter12")
        self.setupLayout.addWidget(self.letter12, 3, 4, 1, 1)
        self.letter51 = QtWidgets.QComboBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.letter51.sizePolicy().hasHeightForWidth())
        self.letter51.setSizePolicy(sizePolicy)
        self.letter51.setMinimumSize(QtCore.QSize(50, 30))
        self.letter51.setObjectName("letter51")
        self.setupLayout.addWidget(self.letter51, 11, 2, 1, 1)
        self.letter21 = QtWidgets.QComboBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.letter21.sizePolicy().hasHeightForWidth())
        self.letter21.setSizePolicy(sizePolicy)
        self.letter21.setMinimumSize(QtCore.QSize(50, 30))
        self.letter21.setObjectName("letter21")
        self.setupLayout.addWidget(self.letter21, 5, 2, 1, 1)
        self.letter32 = QtWidgets.QComboBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.letter32.sizePolicy().hasHeightForWidth())
        self.letter32.setSizePolicy(sizePolicy)
        self.letter32.setMinimumSize(QtCore.QSize(50, 30))
        self.letter32.setObjectName("letter32")
        self.setupLayout.addWidget(self.letter32, 7, 4, 1, 1)
        self.letter44 = QtWidgets.QComboBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.letter44.sizePolicy().hasHeightForWidth())
        self.letter44.setSizePolicy(sizePolicy)
        self.letter44.setMinimumSize(QtCore.QSize(50, 30))
        self.letter44.setObjectName("letter44")
        self.setupLayout.addWidget(self.letter44, 9, 8, 1, 1)
        self.letter24 = QtWidgets.QComboBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.letter24.sizePolicy().hasHeightForWidth())
        self.letter24.setSizePolicy(sizePolicy)
        self.letter24.setMinimumSize(QtCore.QSize(50, 30))
        self.letter24.setObjectName("letter24")
        self.setupLayout.addWidget(self.letter24, 5, 8, 1, 1)
        self.letter50 = QtWidgets.QComboBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.letter50.sizePolicy().hasHeightForWidth())
        self.letter50.setSizePolicy(sizePolicy)
        self.letter50.setMinimumSize(QtCore.QSize(50, 30))
        self.letter50.setObjectName("letter50")
        self.setupLayout.addWidget(self.letter50, 11, 0, 1, 1)
        self.letter42 = QtWidgets.QComboBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.letter42.sizePolicy().hasHeightForWidth())
        self.letter42.setSizePolicy(sizePolicy)
        self.letter42.setMinimumSize(QtCore.QSize(50, 30))
        self.letter42.setObjectName("letter42")
        self.setupLayout.addWidget(self.letter42, 9, 4, 1, 1)
        self.letter03 = QtWidgets.QComboBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.letter03.sizePolicy().hasHeightForWidth())
        self.letter03.setSizePolicy(sizePolicy)
        self.letter03.setMinimumSize(QtCore.QSize(50, 30))
        self.letter03.setObjectName("letter03")
        self.setupLayout.addWidget(self.letter03, 1, 6, 1, 1)
        self.letter30 = QtWidgets.QComboBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.letter30.sizePolicy().hasHeightForWidth())
        self.letter30.setSizePolicy(sizePolicy)
        self.letter30.setMinimumSize(QtCore.QSize(50, 30))
        self.letter30.setObjectName("letter30")
        self.setupLayout.addWidget(self.letter30, 7, 0, 1, 1)
        self.letter55 = QtWidgets.QComboBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.letter55.sizePolicy().hasHeightForWidth())
        self.letter55.setSizePolicy(sizePolicy)
        self.letter55.setMinimumSize(QtCore.QSize(50, 30))
        self.letter55.setObjectName("letter55")
        self.setupLayout.addWidget(self.letter55, 11, 10, 1, 1)
        self.letter15 = QtWidgets.QComboBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.letter15.sizePolicy().hasHeightForWidth())
        self.letter15.setSizePolicy(sizePolicy)
        self.letter15.setMinimumSize(QtCore.QSize(50, 30))
        self.letter15.setObjectName("letter15")
        self.setupLayout.addWidget(self.letter15, 3, 10, 1, 1)
        self.letter41 = QtWidgets.QComboBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.letter41.sizePolicy().hasHeightForWidth())
        self.letter41.setSizePolicy(sizePolicy)
        self.letter41.setMinimumSize(QtCore.QSize(50, 30))
        self.letter41.setObjectName("letter41")
        self.setupLayout.addWidget(self.letter41, 9, 2, 1, 1)
        self.letter43 = QtWidgets.QComboBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.letter43.sizePolicy().hasHeightForWidth())
        self.letter43.setSizePolicy(sizePolicy)
        self.letter43.setMinimumSize(QtCore.QSize(50, 30))
        self.letter43.setObjectName("letter43")
        self.setupLayout.addWidget(self.letter43, 9, 6, 1, 1)
        self.letter54 = QtWidgets.QComboBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.letter54.sizePolicy().hasHeightForWidth())
        self.letter54.setSizePolicy(sizePolicy)
        self.letter54.setMinimumSize(QtCore.QSize(50, 30))
        self.letter54.setObjectName("letter54")
        self.setupLayout.addWidget(self.letter54, 11, 8, 1, 1)
        self.letter35 = QtWidgets.QComboBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.letter35.sizePolicy().hasHeightForWidth())
        self.letter35.setSizePolicy(sizePolicy)
        self.letter35.setMinimumSize(QtCore.QSize(50, 30))
        self.letter35.setObjectName("letter35")
        self.setupLayout.addWidget(self.letter35, 7, 10, 1, 1)
        self.letter11 = QtWidgets.QComboBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.letter11.sizePolicy().hasHeightForWidth())
        self.letter11.setSizePolicy(sizePolicy)
        self.letter11.setMinimumSize(QtCore.QSize(50, 30))
        self.letter11.setObjectName("letter11")
        self.setupLayout.addWidget(self.letter11, 3, 2, 1, 1)
        self.letter13 = QtWidgets.QComboBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.letter13.sizePolicy().hasHeightForWidth())
        self.letter13.setSizePolicy(sizePolicy)
        self.letter13.setMinimumSize(QtCore.QSize(50, 30))
        self.letter13.setObjectName("letter13")
        self.setupLayout.addWidget(self.letter13, 3, 6, 1, 1)
        self.letter33 = QtWidgets.QComboBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.letter33.sizePolicy().hasHeightForWidth())
        self.letter33.setSizePolicy(sizePolicy)
        self.letter33.setMinimumSize(QtCore.QSize(50, 30))
        self.letter33.setObjectName("letter33")
        self.setupLayout.addWidget(self.letter33, 7, 6, 1, 1)
        self.letter23 = QtWidgets.QComboBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.letter23.sizePolicy().hasHeightForWidth())
        self.letter23.setSizePolicy(sizePolicy)
        self.letter23.setMinimumSize(QtCore.QSize(50, 30))
        self.letter23.setObjectName("letter23")
        self.setupLayout.addWidget(self.letter23, 5, 6, 1, 1)
        self.letter04 = QtWidgets.QComboBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.letter04.sizePolicy().hasHeightForWidth())
        self.letter04.setSizePolicy(sizePolicy)
        self.letter04.setMinimumSize(QtCore.QSize(50, 30))
        self.letter04.setObjectName("letter04")
        self.setupLayout.addWidget(self.letter04, 1, 8, 1, 1)
        self.letter25 = QtWidgets.QComboBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.letter25.sizePolicy().hasHeightForWidth())
        self.letter25.setSizePolicy(sizePolicy)
        self.letter25.setMinimumSize(QtCore.QSize(50, 30))
        self.letter25.setObjectName("letter25")
        self.setupLayout.addWidget(self.letter25, 5, 10, 1, 1)
        self.letter10 = QtWidgets.QComboBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.letter10.sizePolicy().hasHeightForWidth())
        self.letter10.setSizePolicy(sizePolicy)
        self.letter10.setMinimumSize(QtCore.QSize(50, 30))
        self.letter10.setObjectName("letter10")
                self.setupLayout.addWidget(self.letter10, 3, 0, 1, 1)
        self.letter22 = QtWidgets.QComboBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.letter22.sizePolicy().hasHeightForWidth())
        self.letter22.setSizePolicy(sizePolicy)
        self.letter22.setMinimumSize(QtCore.QSize(50, 30))
        self.letter22.setObjectName("letter22")
        self.setupLayout.addWidget(self.letter22, 5, 4, 1, 1)
        self.letter52 = QtWidgets.QComboBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.letter52.sizePolicy().hasHeightForWidth())
        self.letter52.setSizePolicy(sizePolicy)
        self.letter52.setMinimumSize(QtCore.QSize(50, 30))
        self.letter52.setObjectName("letter52")
        self.setupLayout.addWidget(self.letter52, 11, 4, 1, 1)
        self.letter40 = QtWidgets.QComboBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.letter40.sizePolicy().hasHeightForWidth())
        self.letter40.setSizePolicy(sizePolicy)
        self.letter40.setMinimumSize(QtCore.QSize(50, 30))
        self.letter40.setObjectName("letter40")
        self.setupLayout.addWidget(self.letter40, 9, 0, 1, 1)
        self.gridLayout_2.addLayout(self.setupLayout, 1, 0, 1, 1)

        self.retranslateUi(Form)
        self.letter00.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Choose boggle size: "))
        self.radioButton.setText(_translate("Form", "4 x 4"))
        self.radioButton_2.setText(_translate("Form", "5 x 5"))
        self.radioButton_3.setText(_translate("Form", "6 x 6"))
        self.pushButton.setText(_translate("Form", "Submit"))
        self.pushButton_2.setText(_translate("Form", "Cancel"))
        self.letter10.setItemText(0, _translate("Form", "A"))
        self.letter10.setItemText(1, _translate("Form", "AN"))
        self.letter10.setItemText(2, _translate("Form", "B"))
        self.letter10.setItemText(3, _translate("Form", "C"))
        self.letter10.setItemText(4, _translate("Form", "D"))
        self.letter10.setItemText(5, _translate("Form", "E"))
        self.letter10.setItemText(6, _translate("Form", "ER"))
        self.letter10.setItemText(7, _translate("Form", "F"))
        self.letter10.setItemText(8, _translate("Form", "G"))
        self.letter10.setItemText(9, _translate("Form", "H"))
        self.letter10.setItemText(10, _translate("Form", "HE"))
        self.letter10.setItemText(11, _translate("Form", "I"))
        self.letter10.setItemText(12, _translate("Form", "IN"))
        self.letter10.setItemText(13, _translate("Form", "J"))
        self.letter10.setItemText(14, _translate("Form", "K"))
        self.letter10.setItemText(15, _translate("Form", "L"))
        self.letter10.setItemText(16, _translate("Form", "M"))
        self.letter10.setItemText(17, _translate("Form", "N"))
        self.letter10.setItemText(18, _translate("Form", "O"))
        self.letter10.setItemText(19, _translate("Form", "P"))
        self.letter10.setItemText(20, _translate("Form", "QU"))
        self.letter10.setItemText(21, _translate("Form", "R"))
        self.letter10.setItemText(22, _translate("Form", "S"))
        self.letter10.setItemText(23, _translate("Form", "T"))
        self.letter10.setItemText(24, _translate("Form", "TH"))
        self.letter10.setItemText(25, _translate("Form", "U"))
        self.letter10.setItemText(26, _translate("Form", "V"))
        self.letter10.setItemText(27, _translate("Form", "W"))
        self.letter10.setItemText(28, _translate("Form", "X"))
        self.letter10.setItemText(29, _translate("Form", "Y"))
        self.letter10.setItemText(30, _translate("Form", "Z"))
        self.letter10.setItemText(31, _translate("Form", "#"))

