# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from gui.customLabel import ImageLabel
from gui.customLineEdit import TypeOnlyLineEdit

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(720, 450)
        MainWindow.setMinimumSize(QtCore.QSize(720, 450))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutMain = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayoutMain.setObjectName("gridLayoutMain")

        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)

        self.gameLayout = QtWidgets.QGridLayout()
        self.gameLayout.setObjectName("gameLayout")
        self.gameTime = QtWidgets.QLabel(self.centralwidget)
        self.gameTime.setSizePolicy(sizePolicy)
        self.gameTime.setMinimumSize(QtCore.QSize(200, 20))
        self.gameTime.setMaximumSize(QtCore.QSize(200, 20))
        self.gameTime.setScaledContents(False)
        self.gameTime.setObjectName("gameTime")
        self.gameLayout.addWidget(self.gameTime, 0, 0, 1, 1)
        self.gameScores = QtWidgets.QLabel(self.centralwidget)
        self.gameScores.setSizePolicy(sizePolicy)
        self.gameScores.setMinimumSize(QtCore.QSize(200, 20))
        self.gameScores.setMaximumSize(QtCore.QSize(200, 20))
        self.gameScores.setScaledContents(False)
        self.gameScores.setObjectName("gameScores")
        self.gameLayout.addWidget(self.gameScores, 1, 0, 1, 1)
        self.playerInput = TypeOnlyLineEdit(self.centralwidget)
        self.playerInput.setSizePolicy(sizePolicy)
        self.playerInput.setMinimumSize(QtCore.QSize(200, 20))
        self.playerInput.setMaximumSize(QtCore.QSize(300, 20))
        self.playerInput.setObjectName("playerInput")
        self.gameLayout.addWidget(self.playerInput, 4, 0, 1, 1)
        self.line2 = QtWidgets.QFrame(self.centralwidget)
        self.line2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line2.setObjectName("line2")
        self.gameLayout.addWidget(self.line2, 6, 0, 1, 1)
        self.wordListDisplay = QtWidgets.QTextBrowser(self.centralwidget)
        self.wordListDisplay.setSizePolicy(sizePolicy)
        self.wordListDisplay.setMinimumSize(QtCore.QSize(200, 100))
        self.wordListDisplay.setMaximumSize(QtCore.QSize(200, 16777215))
        self.wordListDisplay.setSizeIncrement(QtCore.QSize(0, 0))
        self.wordListDisplay.setObjectName("wordListDisplay")
        self.gameLayout.addWidget(self.wordListDisplay, 7, 0, 1, 1)
        self.gridLayoutMain.addLayout(self.gameLayout, 0, 1, 2, 1)

        self.introLayout = QtWidgets.QHBoxLayout()
        self.introLayout.setObjectName("introLayout")
        self.gameIntro = QtWidgets.QLabel(self.centralwidget)
        self.gameIntro.setMinimumSize(QtCore.QSize(0, 0))
        self.gameIntro.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.gameIntro.setScaledContents(True)
        self.gameIntro.setAlignment(QtCore.Qt.AlignCenter)
        self.gameIntro.setObjectName("gameIntro")
        self.introLayout.addWidget(self.gameIntro)
        self.gameNew = QtWidgets.QPushButton(self.centralwidget)
        self.gameNew.setMinimumSize(QtCore.QSize(150, 35))
        self.gameNew.setMaximumSize(QtCore.QSize(200, 35))
        self.gameNew.setObjectName("gameNew")
        self.introLayout.addWidget(self.gameNew)
        self.gridLayoutMain.addLayout(self.introLayout, 0, 0, 1, 1)
        
        self.boardLayout = QtWidgets.QGridLayout()
        self.boardLayout.setSpacing(0)
        self.boardLayout.setObjectName("boardLayout")

        letterFont = QtGui.QFont()
        letterFont.setFamily("Superclarendon")
        letterFont.setPointSize(24) 

        self.letter00 = ImageLabel(self.centralwidget)
        self.letter00.setPosition(0, 0)
        self.letter00.setPixmap(QtGui.QPixmap("images/letter_A.png"))
        self.letter00.setFont(letterFont)
        self.letter00.setMouseTracking(True)
        self.letter00.setScaledContents(True)
        self.letter00.setObjectName("letter00")
        self.boardLayout.addWidget(self.letter00, 0, 0, 1, 1)
        self.letter01 = ImageLabel(self.centralwidget)
        self.letter01.setPosition(0, 1)
        self.letter01.setPixmap(QtGui.QPixmap("images/letter_B.png"))
        self.letter01.setFont(letterFont)
        self.letter01.setMouseTracking(True)
        self.letter01.setScaledContents(True)
        self.letter01.setObjectName("letter01")
        self.boardLayout.addWidget(self.letter01, 0, 2, 1, 1)
        self.letter02 = ImageLabel(self.centralwidget)
        self.letter02.setPosition(0, 2)
        self.letter02.setPixmap(QtGui.QPixmap("images/letter_C.png"))
        self.letter02.setFont(letterFont)
        self.letter02.setMouseTracking(True)
        self.letter02.setScaledContents(True)
        self.letter02.setObjectName("letter02")
        self.boardLayout.addWidget(self.letter02, 0, 4, 1, 1)
        self.letter03 = ImageLabel(self.centralwidget)
        self.letter03.setPosition(0, 4)
        self.letter03.setPixmap(QtGui.QPixmap("images/letter_D.png"))
        self.letter03.setFont(letterFont)
        self.letter03.setMouseTracking(True)
        self.letter03.setScaledContents(True)
        self.letter03.setObjectName("letter03")
        self.boardLayout.addWidget(self.letter03, 0, 6, 1, 1)
        self.letter04 = ImageLabel(self.centralwidget)
        self.letter04.setPosition(0, 4)
        self.letter04.setPixmap(QtGui.QPixmap("images/letter_E.png"))
        self.letter04.setFont(letterFont)
        self.letter04.setMouseTracking(True)
        self.letter04.setScaledContents(True)
        self.letter04.setObjectName("letter04")
        self.boardLayout.addWidget(self.letter04, 0, 8, 1, 1)
        self.letter05 = ImageLabel(self.centralwidget)
        self.letter05.setPosition(0, 5)
        self.letter05.setPixmap(QtGui.QPixmap("images/letter_AN.png"))
        self.letter05.setFont(letterFont)
        self.letter05.setMouseTracking(True)
        self.letter05.setScaledContents(True)
        self.letter05.setObjectName("letter05")
        self.boardLayout.addWidget(self.letter05, 0, 10, 1, 1)
        
        self.linkh00 = QtWidgets.QLabel(self.centralwidget)
        self.linkh00.setPixmap(QtGui.QPixmap("images/space_right.png"))
        self.linkh00.setObjectName("linkh00")
        self.boardLayout.addWidget(self.linkh00, 0, 1, 1, 1)
        self.linkh01 = QtWidgets.QLabel(self.centralwidget)
        self.linkh01.setPixmap(QtGui.QPixmap("images/space_right.png"))
        self.linkh01.setObjectName("linkh01")
        self.boardLayout.addWidget(self.linkh01, 0, 3, 1, 1)
        self.linkh02 = QtWidgets.QLabel(self.centralwidget)
        self.linkh02.setPixmap(QtGui.QPixmap("images/space_right.png"))
        self.linkh02.setObjectName("linkh02")
        self.boardLayout.addWidget(self.linkh02, 0, 5, 1, 1)
        self.linkh03 = QtWidgets.QLabel(self.centralwidget)
        self.linkh03.setPixmap(QtGui.QPixmap("images/space_right.png"))
        self.linkh03.setObjectName("linkh03")
        self.boardLayout.addWidget(self.linkh03, 0, 7, 1, 1)
        self.linkh04 = QtWidgets.QLabel(self.centralwidget)
        self.linkh04.setPixmap(QtGui.QPixmap("images/space_right.png"))
        self.linkh04.setObjectName("linkh04")
        self.boardLayout.addWidget(self.linkh04, 0, 9, 1, 1)
        
        self.linkv00 = QtWidgets.QLabel(self.centralwidget)
        self.linkv00.setPixmap(QtGui.QPixmap("images/space_down.png"))
        self.linkv00.setAlignment(QtCore.Qt.AlignCenter)
        self.linkv00.setObjectName("linkv00")
        self.boardLayout.addWidget(self.linkv00, 1, 0, 1, 1)
        self.linkv01 = QtWidgets.QLabel(self.centralwidget)
        self.linkv01.setPixmap(QtGui.QPixmap("images/space_down.png"))
        self.linkv01.setAlignment(QtCore.Qt.AlignCenter)
        self.linkv01.setObjectName("linkv01")
        self.boardLayout.addWidget(self.linkv01, 1, 2, 1, 1)
        self.linkv02 = QtWidgets.QLabel(self.centralwidget)
        self.linkv02.setPixmap(QtGui.QPixmap("images/space_down.png"))
        self.linkv02.setAlignment(QtCore.Qt.AlignCenter)
        self.linkv02.setObjectName("linkv02")
        self.boardLayout.addWidget(self.linkv02, 1, 4, 1, 1)
        self.linkv03 = QtWidgets.QLabel(self.centralwidget)
        self.linkv03.setPixmap(QtGui.QPixmap("images/space_down.png"))
        self.linkv03.setAlignment(QtCore.Qt.AlignCenter)
        self.linkv03.setObjectName("linkv03")
        self.boardLayout.addWidget(self.linkv03, 1, 6, 1, 1)
        self.linkv04 = QtWidgets.QLabel(self.centralwidget)
        self.linkv04.setPixmap(QtGui.QPixmap("images/space_down.png"))
        self.linkv04.setAlignment(QtCore.Qt.AlignCenter)
        self.linkv04.setObjectName("linkv04")
        self.boardLayout.addWidget(self.linkv04, 1, 8, 1, 1)
        self.linkv05 = QtWidgets.QLabel(self.centralwidget)
        self.linkv05.setPixmap(QtGui.QPixmap("images/space_down.png"))
        self.linkv05.setAlignment(QtCore.Qt.AlignCenter)
        self.linkv05.setObjectName("linkv05")
        self.boardLayout.addWidget(self.linkv05, 1, 10, 1, 1)
        
        self.linkx00 = QtWidgets.QLabel(self.centralwidget)
        self.linkx00.setPixmap(QtGui.QPixmap("images/space_cross.png"))
        self.linkx00.setScaledContents(False)
        self.linkx00.setObjectName("linkx00")
        self.boardLayout.addWidget(self.linkx00, 1, 1, 1, 1)
        self.linkx01 = QtWidgets.QLabel(self.centralwidget)
        self.linkx01.setPixmap(QtGui.QPixmap("images/space_cross.png"))
        self.linkx01.setScaledContents(False)
        self.linkx01.setObjectName("linkx01")
        self.boardLayout.addWidget(self.linkx01, 1, 3, 1, 1)
        self.linkx02 = QtWidgets.QLabel(self.centralwidget)
        self.linkx02.setPixmap(QtGui.QPixmap("images/space_cross.png"))
        self.linkx02.setScaledContents(False)
        self.linkx02.setObjectName("linkx02")
        self.boardLayout.addWidget(self.linkx02, 1, 5, 1, 1)
        self.linkx03 = QtWidgets.QLabel(self.centralwidget)
        self.linkx03.setPixmap(QtGui.QPixmap("images/space_cross.png"))
        self.linkx03.setScaledContents(False)
        self.linkx03.setObjectName("linkx03")
        self.boardLayout.addWidget(self.linkx03, 1, 7, 1, 1)
        self.linkx04 = QtWidgets.QLabel(self.centralwidget)
        self.linkx04.setPixmap(QtGui.QPixmap("images/space_cross.png"))
        self.linkx04.setScaledContents(False)
        self.linkx04.setObjectName("linkx04")
        self.boardLayout.addWidget(self.linkx04, 1, 9, 1, 1)
        
        #---------------------------------------------------

        self.letter10 = ImageLabel(self.centralwidget)
        self.letter10.setPosition(1, 0)
        self.letter10.setPixmap(QtGui.QPixmap("images/letter_F.png"))
        self.letter10.setFont(letterFont)
        self.letter10.setMouseTracking(True)
        self.letter10.setScaledContents(True)
        self.letter10.setObjectName("letter10")
        self.boardLayout.addWidget(self.letter10, 2, 0, 1, 1)
        self.letter11 = ImageLabel(self.centralwidget)
        self.letter11.setPosition(1, 1)
        self.letter11.setPixmap(QtGui.QPixmap("images/letter_G.png"))
        self.letter11.setFont(letterFont)
        self.letter11.setMouseTracking(True)
        self.letter11.setScaledContents(True)
        self.letter11.setObjectName("letter11")
        self.boardLayout.addWidget(self.letter11, 2, 2, 1, 1)
        self.letter12 = ImageLabel(self.centralwidget)
        self.letter12.setPosition(1, 2)
        self.letter12.setPixmap(QtGui.QPixmap("images/letter_H.png"))
        self.letter12.setFont(letterFont)
        self.letter12.setMouseTracking(True)
        self.letter12.setScaledContents(True)
        self.letter12.setObjectName("letter12")
        self.boardLayout.addWidget(self.letter12, 2, 4, 1, 1)
        self.letter13 = ImageLabel(self.centralwidget)
        self.letter13.setPosition(1, 3)
        self.letter13.setPixmap(QtGui.QPixmap("images/letter_I.png"))
        self.letter13.setFont(letterFont)
        self.letter13.setMouseTracking(True)
        self.letter13.setScaledContents(True)
        self.letter13.setObjectName("letter13")
        self.boardLayout.addWidget(self.letter13, 2, 6, 1, 1)
        self.letter14 = ImageLabel(self.centralwidget)
        self.letter14.setPosition(1, 4)
        self.letter14.setPixmap(QtGui.QPixmap("images/letter_J.png"))
        self.letter14.setFont(letterFont)
        self.letter14.setMouseTracking(True)
        self.letter14.setScaledContents(True)
        self.letter14.setObjectName("letter14")
        self.boardLayout.addWidget(self.letter14, 2, 8, 1, 1)
        self.letter15 = ImageLabel(self.centralwidget)
        self.letter15.setPosition(1, 5)
        self.letter15.setPixmap(QtGui.QPixmap("images/letter_ER.png"))
        self.letter15.setFont(letterFont)
        self.letter15.setMouseTracking(True)
        self.letter15.setScaledContents(True)
        self.letter15.setObjectName("letter15")
        self.boardLayout.addWidget(self.letter15, 2, 10, 1, 1)
        
        self.linkh10 = QtWidgets.QLabel(self.centralwidget)
        self.linkh10.setPixmap(QtGui.QPixmap("images/space_right.png"))
        self.linkh10.setObjectName("linkh10")
        self.boardLayout.addWidget(self.linkh10, 2, 1, 1, 1)
        self.linkh11 = QtWidgets.QLabel(self.centralwidget)
        self.linkh11.setPixmap(QtGui.QPixmap("images/space_right.png"))
        self.linkh11.setAlignment(QtCore.Qt.AlignCenter)
        self.linkh11.setObjectName("linkh11")
        self.boardLayout.addWidget(self.linkh11, 2, 3, 1, 1)
        self.linkh12 = QtWidgets.QLabel(self.centralwidget)
        self.linkh12.setPixmap(QtGui.QPixmap("images/space_right.png"))
        self.linkh12.setObjectName("linkh12")
        self.boardLayout.addWidget(self.linkh12, 2, 5, 1, 1)
        self.linkh13 = QtWidgets.QLabel(self.centralwidget)
        self.linkh13.setPixmap(QtGui.QPixmap("images/space_right.png"))
        self.linkh13.setObjectName("linkh13")
        self.boardLayout.addWidget(self.linkh13, 2, 7, 1, 1)
        self.linkh14 = QtWidgets.QLabel(self.centralwidget)
        self.linkh14.setPixmap(QtGui.QPixmap("images/space_right.png"))
        self.linkh14.setObjectName("linkh14")
        self.boardLayout.addWidget(self.linkh14, 2, 9, 1, 1)
        
        self.linkv10 = QtWidgets.QLabel(self.centralwidget)
        self.linkv10.setPixmap(QtGui.QPixmap("images/space_down.png"))
        self.linkv10.setAlignment(QtCore.Qt.AlignCenter)
        self.linkv10.setObjectName("linkv10")
        self.boardLayout.addWidget(self.linkv10, 3, 0, 1, 1)
        self.linkv11 = QtWidgets.QLabel(self.centralwidget)
        self.linkv11.setPixmap(QtGui.QPixmap("images/space_down.png"))
        self.linkv11.setAlignment(QtCore.Qt.AlignCenter)
        self.linkv11.setObjectName("linkv11")
        self.boardLayout.addWidget(self.linkv11, 3, 2, 1, 1)
        self.linkv12 = QtWidgets.QLabel(self.centralwidget)
        self.linkv12.setPixmap(QtGui.QPixmap("images/space_down.png"))
        self.linkv12.setAlignment(QtCore.Qt.AlignCenter)
        self.linkv12.setObjectName("linkv12")
        self.boardLayout.addWidget(self.linkv12, 3, 4, 1, 1)
        self.linkv13 = QtWidgets.QLabel(self.centralwidget)
        self.linkv13.setPixmap(QtGui.QPixmap("images/space_down.png"))
        self.linkv13.setAlignment(QtCore.Qt.AlignCenter)
        self.linkv13.setObjectName("linkv13")
        self.boardLayout.addWidget(self.linkv13, 3, 6, 1, 1)
        self.linkv14 = QtWidgets.QLabel(self.centralwidget)
        self.linkv14.setPixmap(QtGui.QPixmap("images/space_down.png"))
        self.linkv14.setAlignment(QtCore.Qt.AlignCenter)
        self.linkv14.setObjectName("linkv14")
        self.boardLayout.addWidget(self.linkv14, 3, 8, 1, 1)
        self.linkv15 = QtWidgets.QLabel(self.centralwidget)
        self.linkv15.setPixmap(QtGui.QPixmap("images/space_down.png"))
        self.linkv15.setAlignment(QtCore.Qt.AlignCenter)
        self.linkv15.setObjectName("linkv15")
        self.boardLayout.addWidget(self.linkv15, 3, 10, 1, 1)
        
        self.linkx10 = QtWidgets.QLabel(self.centralwidget)
        self.linkx10.setPixmap(QtGui.QPixmap("images/space_cross.png"))
        self.linkx10.setObjectName("linkx10")
        self.boardLayout.addWidget(self.linkx10, 3, 1, 1, 1)
        self.linkx11 = QtWidgets.QLabel(self.centralwidget)
        self.linkx11.setPixmap(QtGui.QPixmap("images/space_cross.png"))
        self.linkx11.setObjectName("linkx11")
        self.boardLayout.addWidget(self.linkx11, 3, 3, 1, 1)
        self.linkx12 = QtWidgets.QLabel(self.centralwidget)
        self.linkx12.setPixmap(QtGui.QPixmap("images/space_cross.png"))
        self.linkx12.setObjectName("linkx12")
        self.boardLayout.addWidget(self.linkx12, 3, 5, 1, 1)
        self.linkx13 = QtWidgets.QLabel(self.centralwidget)
        self.linkx13.setPixmap(QtGui.QPixmap("images/space_cross.png"))
        self.linkx13.setObjectName("linkx13")
        self.boardLayout.addWidget(self.linkx13, 3, 7, 1, 1)
        self.linkx14 = QtWidgets.QLabel(self.centralwidget)
        self.linkx14.setPixmap(QtGui.QPixmap("images/space_cross.png"))
        self.linkx14.setObjectName("linkx14")
        self.boardLayout.addWidget(self.linkx14, 3, 9, 1, 1)
        
        #---------------------------------------------------
        
        self.letter20 = ImageLabel(self.centralwidget)
        self.letter20.setPosition(2, 0)
        self.letter20.setPixmap(QtGui.QPixmap("images/letter_K.png"))
        self.letter20.setFont(letterFont)
        self.letter20.setMouseTracking(True)
        self.letter20.setScaledContents(True)
        self.letter20.setObjectName("letter20")
        self.boardLayout.addWidget(self.letter20, 4, 0, 1, 1)
        self.letter21 = ImageLabel(self.centralwidget)
        self.letter21.setPosition(2, 1)
        self.letter21.setPixmap(QtGui.QPixmap("images/letter_L.png"))
        self.letter21.setFont(letterFont)
        self.letter21.setMouseTracking(True)
        self.letter21.setScaledContents(True)
        self.letter21.setObjectName("letter21")
        self.boardLayout.addWidget(self.letter21, 4, 2, 1, 1)
        self.letter22 = ImageLabel(self.centralwidget)
        self.letter22.setPosition(2, 2)
        self.letter22.setPixmap(QtGui.QPixmap("images/letter_M.png"))
        self.letter22.setFont(letterFont)
        self.letter22.setMouseTracking(True)
        self.letter22.setScaledContents(True)
        self.letter22.setObjectName("letter22")
        self.boardLayout.addWidget(self.letter22, 4, 4, 1, 1)
        self.letter23 = ImageLabel(self.centralwidget)
        self.letter23.setPosition(2, 3)
        self.letter23.setPixmap(QtGui.QPixmap("images/letter_N.png"))
        self.letter23.setFont(letterFont)
        self.letter23.setMouseTracking(True)
        self.letter23.setScaledContents(True)
        self.letter23.setObjectName("letter23")
        self.boardLayout.addWidget(self.letter23, 4, 6, 1, 1)
        self.letter24 = ImageLabel(self.centralwidget)
        self.letter24.setPosition(2, 4)
        self.letter24.setPixmap(QtGui.QPixmap("images/letter_O.png"))
        self.letter24.setFont(letterFont)
        self.letter24.setMouseTracking(True)
        self.letter24.setScaledContents(True)
        self.letter24.setObjectName("letter24")
        self.boardLayout.addWidget(self.letter24, 4, 8, 1, 1)
        self.letter25 = ImageLabel(self.centralwidget)
        self.letter25.setPosition(2, 5)
        self.letter25.setPixmap(QtGui.QPixmap("images/letter_HE.png"))
        self.letter25.setFont(letterFont)
        self.letter25.setMouseTracking(True)
        self.letter25.setScaledContents(True)
        self.letter25.setObjectName("letter25")
        self.boardLayout.addWidget(self.letter25, 4, 10, 1, 1)
        
        self.linkh20 = QtWidgets.QLabel(self.centralwidget)
        self.linkh20.setPixmap(QtGui.QPixmap("images/space_right.png"))
        self.linkh20.setObjectName("linkh20")
        self.boardLayout.addWidget(self.linkh20, 4, 1, 1, 1)
        self.linkh21 = QtWidgets.QLabel(self.centralwidget)
        self.linkh21.setPixmap(QtGui.QPixmap("images/space_right.png"))
        self.linkh21.setObjectName("linkh21")
        self.boardLayout.addWidget(self.linkh21, 4, 3, 1, 1)
        self.linkh22 = QtWidgets.QLabel(self.centralwidget)
        self.linkh22.setPixmap(QtGui.QPixmap("images/space_right.png"))
        self.linkh22.setObjectName("linkh22")
        self.boardLayout.addWidget(self.linkh22, 4, 5, 1, 1)
        self.linkh23 = QtWidgets.QLabel(self.centralwidget)
        self.linkh23.setPixmap(QtGui.QPixmap("images/space_right.png"))
        self.linkh23.setObjectName("linkh23")
        self.boardLayout.addWidget(self.linkh23, 4, 7, 1, 1)
        self.linkh24 = QtWidgets.QLabel(self.centralwidget)
        self.linkh24.setPixmap(QtGui.QPixmap("images/space_right.png"))
        self.linkh24.setObjectName("linkh24")
        self.boardLayout.addWidget(self.linkh24, 4, 9, 1, 1)
        
        self.linkv20 = QtWidgets.QLabel(self.centralwidget)
        self.linkv20.setPixmap(QtGui.QPixmap("images/space_down.png"))
        self.linkv20.setAlignment(QtCore.Qt.AlignCenter)
        self.linkv20.setObjectName("linkv20")
        self.boardLayout.addWidget(self.linkv20, 5, 0, 1, 1)
        self.linkv21 = QtWidgets.QLabel(self.centralwidget)
        self.linkv21.setPixmap(QtGui.QPixmap("images/space_down.png"))
        self.linkv21.setAlignment(QtCore.Qt.AlignCenter)
        self.linkv21.setObjectName("linkv21")
        self.boardLayout.addWidget(self.linkv21, 5, 2, 1, 1)
        self.linkv22 = QtWidgets.QLabel(self.centralwidget)
        self.linkv22.setPixmap(QtGui.QPixmap("images/space_down.png"))
        self.linkv22.setAlignment(QtCore.Qt.AlignCenter)
        self.linkv22.setObjectName("linkv22")
        self.boardLayout.addWidget(self.linkv22, 5, 4, 1, 1)
        self.linkv23 = QtWidgets.QLabel(self.centralwidget)
        self.linkv23.setPixmap(QtGui.QPixmap("images/space_down.png"))
        self.linkv23.setAlignment(QtCore.Qt.AlignCenter)
        self.linkv23.setObjectName("linkv23")
        self.boardLayout.addWidget(self.linkv23, 5, 6, 1, 1)
        self.linkv24 = QtWidgets.QLabel(self.centralwidget)
        self.linkv24.setPixmap(QtGui.QPixmap("images/space_down.png"))
        self.linkv24.setAlignment(QtCore.Qt.AlignCenter)
        self.linkv24.setObjectName("linkv24")
        self.boardLayout.addWidget(self.linkv24, 5, 8, 1, 1)
        self.linkv25 = QtWidgets.QLabel(self.centralwidget)
        self.linkv25.setPixmap(QtGui.QPixmap("images/space_down.png"))
        self.linkv25.setAlignment(QtCore.Qt.AlignCenter)
        self.linkv25.setObjectName("linkv25")
        self.boardLayout.addWidget(self.linkv25, 5, 10, 1, 1)
        
        self.linkx20 = QtWidgets.QLabel(self.centralwidget)
        self.linkx20.setPixmap(QtGui.QPixmap("images/space_cross.png"))
        self.linkx20.setObjectName("linkx20")
        self.boardLayout.addWidget(self.linkx20, 5, 1, 1, 1)
        self.linkx21 = QtWidgets.QLabel(self.centralwidget)
        self.linkx21.setPixmap(QtGui.QPixmap("images/space_cross.png"))
        self.linkx21.setObjectName("linkx21")
        self.boardLayout.addWidget(self.linkx21, 5, 3, 1, 1)
        self.linkx22 = QtWidgets.QLabel(self.centralwidget)
        self.linkx22.setPixmap(QtGui.QPixmap("images/space_cross.png"))
        self.linkx22.setObjectName("linkx22")
        self.boardLayout.addWidget(self.linkx22, 5, 5, 1, 1)
        self.linkx23 = QtWidgets.QLabel(self.centralwidget)
        self.linkx23.setPixmap(QtGui.QPixmap("images/space_cross.png"))
        self.linkx23.setObjectName("linkx23")
        self.boardLayout.addWidget(self.linkx23, 5, 7, 1, 1)
        self.linkx24 = QtWidgets.QLabel(self.centralwidget)
        self.linkx24.setPixmap(QtGui.QPixmap("images/space_cross.png"))
        self.linkx24.setObjectName("linkx24")
        self.boardLayout.addWidget(self.linkx24, 5, 9, 1, 1)
        
        #---------------------------------------------------
        
        self.letter30 = ImageLabel(self.centralwidget)
        self.letter30.setPosition(3, 0)
        self.letter30.setPixmap(QtGui.QPixmap("images/letter_P.png"))
        self.letter30.setFont(letterFont)
        self.letter30.setMouseTracking(True)
        self.letter30.setScaledContents(True)
        self.letter30.setObjectName("letter30")
        self.boardLayout.addWidget(self.letter30, 6, 0, 1, 1)
        self.letter31 = ImageLabel(self.centralwidget)
        self.letter31.setPosition(3, 1)
        self.letter31.setPixmap(QtGui.QPixmap("images/letter_QU.png"))
        self.letter31.setFont(letterFont)
        self.letter31.setMouseTracking(True)
        self.letter31.setScaledContents(True)
        self.letter31.setObjectName("letter31")
        self.boardLayout.addWidget(self.letter31, 6, 2, 1, 1)
        self.letter32 = ImageLabel(self.centralwidget)
        self.letter32.setPosition(3, 2)
        self.letter32.setPixmap(QtGui.QPixmap("images/letter_R.png"))
        self.letter32.setFont(letterFont)
        self.letter32.setMouseTracking(True)
        self.letter32.setScaledContents(True)
        self.letter32.setObjectName("letter32")
        self.boardLayout.addWidget(self.letter32, 6, 4, 1, 1)
        self.letter33 = ImageLabel(self.centralwidget)
        self.letter33.setPosition(3, 3)
        self.letter33.setPixmap(QtGui.QPixmap("images/letter_S.png"))
        self.letter33.setFont(letterFont)
        self.letter33.setMouseTracking(True)
        self.letter33.setScaledContents(True)
        self.letter33.setObjectName("letter33")
        self.boardLayout.addWidget(self.letter33, 6, 6, 1, 1)
        self.letter34 = ImageLabel(self.centralwidget)
        self.letter34.setPosition(3, 4)
        self.letter34.setPixmap(QtGui.QPixmap("images/letter_T.png"))
        self.letter34.setFont(letterFont)
        self.letter34.setMouseTracking(True)
        self.letter34.setScaledContents(True)
        self.letter34.setObjectName("letter34")
        self.boardLayout.addWidget(self.letter34, 6, 8, 1, 1)
        self.letter35 = ImageLabel(self.centralwidget)
        self.letter35.setPosition(3, 5)
        self.letter35.setPixmap(QtGui.QPixmap("images/letter_IN.png"))
        self.letter35.setFont(letterFont)
        self.letter35.setMouseTracking(True)
        self.letter35.setScaledContents(True)
        self.letter35.setObjectName("letter35")
        self.boardLayout.addWidget(self.letter35, 6, 10, 1, 1)
        
        self.linkh30 = QtWidgets.QLabel(self.centralwidget)
        self.linkh30.setPixmap(QtGui.QPixmap("images/space_right.png"))
        self.linkh30.setObjectName("linkh30")
        self.boardLayout.addWidget(self.linkh30, 6, 1, 1, 1)
        self.linkh31 = QtWidgets.QLabel(self.centralwidget)
        self.linkh31.setPixmap(QtGui.QPixmap("images/space_right.png"))
        self.linkh31.setObjectName("linkh31")
        self.boardLayout.addWidget(self.linkh31, 6, 3, 1, 1)
        self.linkh32 = QtWidgets.QLabel(self.centralwidget)
        self.linkh32.setPixmap(QtGui.QPixmap("images/space_right.png"))
        self.linkh32.setObjectName("linkh32")
        self.boardLayout.addWidget(self.linkh32, 6, 5, 1, 1)
        self.linkh33 = QtWidgets.QLabel(self.centralwidget)
        self.linkh33.setPixmap(QtGui.QPixmap("images/space_right.png"))
        self.linkh33.setObjectName("linkh33")
        self.boardLayout.addWidget(self.linkh33, 6, 7, 1, 1)
        self.linkh34 = QtWidgets.QLabel(self.centralwidget)
        self.linkh34.setPixmap(QtGui.QPixmap("images/space_right.png"))
        self.linkh34.setObjectName("linkh34")
        self.boardLayout.addWidget(self.linkh34, 6, 9, 1, 1)
        
        self.linkv30 = QtWidgets.QLabel(self.centralwidget)
        self.linkv30.setPixmap(QtGui.QPixmap("images/space_down.png"))
        self.linkv30.setAlignment(QtCore.Qt.AlignCenter)
        self.linkv30.setObjectName("linkv30")
        self.boardLayout.addWidget(self.linkv30, 7, 0, 1, 1)
        self.linkv31 = QtWidgets.QLabel(self.centralwidget)
        self.linkv31.setPixmap(QtGui.QPixmap("images/space_down.png"))
        self.linkv31.setAlignment(QtCore.Qt.AlignCenter)
        self.linkv31.setObjectName("linkv31")
        self.boardLayout.addWidget(self.linkv31, 7, 2, 1, 1)
        self.linkv32 = QtWidgets.QLabel(self.centralwidget)
        self.linkv32.setPixmap(QtGui.QPixmap("images/space_down.png"))
        self.linkv32.setAlignment(QtCore.Qt.AlignCenter)
        self.linkv32.setObjectName("linkv32")
        self.boardLayout.addWidget(self.linkv32, 7, 4, 1, 1)
        self.linkv33 = QtWidgets.QLabel(self.centralwidget)
        self.linkv33.setPixmap(QtGui.QPixmap("images/space_down.png"))
        self.linkv33.setAlignment(QtCore.Qt.AlignCenter)
        self.linkv33.setObjectName("linkv33")
        self.boardLayout.addWidget(self.linkv33, 7, 6, 1, 1)
        self.linkv34 = QtWidgets.QLabel(self.centralwidget)
        self.linkv34.setPixmap(QtGui.QPixmap("images/space_down.png"))
        self.linkv34.setAlignment(QtCore.Qt.AlignCenter)
        self.linkv34.setObjectName("linkv34")
        self.boardLayout.addWidget(self.linkv34, 7, 8, 1, 1)
        self.linkv35 = QtWidgets.QLabel(self.centralwidget)
        self.linkv35.setPixmap(QtGui.QPixmap("images/space_down.png"))
        self.linkv35.setAlignment(QtCore.Qt.AlignCenter)
        self.linkv35.setObjectName("linkv35")
        self.boardLayout.addWidget(self.linkv35, 7, 10, 1, 1)
        
        self.linkx30 = QtWidgets.QLabel(self.centralwidget)
        self.linkx30.setPixmap(QtGui.QPixmap("images/space_cross.png"))
        self.linkx30.setObjectName("linkx30")
        self.boardLayout.addWidget(self.linkx30, 7, 1, 1, 1)
        self.linkx31 = QtWidgets.QLabel(self.centralwidget)
        self.linkx31.setPixmap(QtGui.QPixmap("images/space_cross.png"))
        self.linkx31.setObjectName("linkx31")
        self.boardLayout.addWidget(self.linkx31, 7, 3, 1, 1)
        self.linkx32 = QtWidgets.QLabel(self.centralwidget)
        self.linkx32.setPixmap(QtGui.QPixmap("images/space_cross.png"))
        self.linkx32.setObjectName("linkx32")
        self.boardLayout.addWidget(self.linkx32, 7, 5, 1, 1)
        self.linkx33 = QtWidgets.QLabel(self.centralwidget)
        self.linkx33.setPixmap(QtGui.QPixmap("images/space_cross.png"))
        self.linkx33.setObjectName("linkx33")
        self.boardLayout.addWidget(self.linkx33, 7, 7, 1, 1)
        self.linkx34 = QtWidgets.QLabel(self.centralwidget)
        self.linkx34.setPixmap(QtGui.QPixmap("images/space_cross.png"))
        self.linkx34.setObjectName("linkx34")
        self.boardLayout.addWidget(self.linkx34, 7, 9, 1, 1)
        
        #---------------------------------------------------
        
        self.letter40 = ImageLabel(self.centralwidget)
        self.letter40.setPosition(4, 0)
        self.letter40.setPixmap(QtGui.QPixmap("images/letter_U.png"))
        self.letter40.setFont(letterFont)
        self.letter40.setMouseTracking(True)
        self.letter40.setScaledContents(True)
        self.letter40.setObjectName("letter40")
        self.boardLayout.addWidget(self.letter40, 8, 0, 1, 1)
        self.letter41 = ImageLabel(self.centralwidget)
        self.letter41.setPosition(4, 1)
        self.letter41.setPixmap(QtGui.QPixmap("images/letter_V.png"))
        self.letter41.setFont(letterFont)
        self.letter41.setMouseTracking(True)
        self.letter41.setScaledContents(True)
        self.letter41.setObjectName("letter41")
        self.boardLayout.addWidget(self.letter41, 8, 2, 1, 1)
        self.letter42 = ImageLabel(self.centralwidget)
        self.letter42.setPosition(4, 2)
        self.letter42.setPixmap(QtGui.QPixmap("images/letter_W.png"))
        self.letter42.setFont(letterFont)
        self.letter42.setMouseTracking(True)
        self.letter42.setScaledContents(True)
        self.letter42.setObjectName("letter42")
        self.boardLayout.addWidget(self.letter42, 8, 4, 1, 1)
        self.letter43 = ImageLabel(self.centralwidget)
        self.letter43.setPosition(4, 3)
        self.letter43.setPixmap(QtGui.QPixmap("images/letter_X.png"))
        self.letter43.setFont(letterFont)
        self.letter43.setMouseTracking(True)
        self.letter43.setScaledContents(True)
        self.letter43.setObjectName("letter43")
        self.boardLayout.addWidget(self.letter43, 8, 6, 1, 1)
        self.letter44 = ImageLabel(self.centralwidget)
        self.letter44.setPosition(4, 4)
        self.letter44.setPixmap(QtGui.QPixmap("images/letter_Y.png"))
        self.letter44.setFont(letterFont)
        self.letter44.setMouseTracking(True)
        self.letter44.setScaledContents(True)
        self.letter44.setObjectName("letter44")
        self.boardLayout.addWidget(self.letter44, 8, 8, 1, 1)
        self.letter45 = ImageLabel(self.centralwidget)
        self.letter45.setPosition(4, 5)
        self.letter45.setPixmap(QtGui.QPixmap("images/letter_TH.png"))
        self.letter45.setFont(letterFont)
        self.letter45.setMouseTracking(True)
        self.letter45.setScaledContents(True)
        self.letter45.setObjectName("letter45")
        self.boardLayout.addWidget(self.letter45, 8, 10, 1, 1)
        
        self.linkh40 = QtWidgets.QLabel(self.centralwidget)
        self.linkh40.setPixmap(QtGui.QPixmap("images/space_right.png"))
        self.linkh40.setObjectName("linkh40")
        self.boardLayout.addWidget(self.linkh40, 8, 1, 1, 1)
        self.linkh41 = QtWidgets.QLabel(self.centralwidget)
        self.linkh41.setPixmap(QtGui.QPixmap("images/space_right.png"))
        self.linkh41.setObjectName("linkh41")
        self.boardLayout.addWidget(self.linkh41, 8, 3, 1, 1)
        self.linkh42 = QtWidgets.QLabel(self.centralwidget)
        self.linkh42.setPixmap(QtGui.QPixmap("images/space_right.png"))
        self.linkh42.setObjectName("linkh42")
        self.boardLayout.addWidget(self.linkh42, 8, 5, 1, 1)
        self.linkh43 = QtWidgets.QLabel(self.centralwidget)
        self.linkh43.setPixmap(QtGui.QPixmap("images/space_right.png"))
        self.linkh43.setObjectName("linkh43")
        self.boardLayout.addWidget(self.linkh43, 8, 7, 1, 1)
        self.linkh44 = QtWidgets.QLabel(self.centralwidget)
        self.linkh44.setPixmap(QtGui.QPixmap("images/space_right.png"))
        self.linkh44.setObjectName("linkh44")
        self.boardLayout.addWidget(self.linkh44, 8, 9, 1, 1)
        
        self.linkv40 = QtWidgets.QLabel(self.centralwidget)
        self.linkv40.setPixmap(QtGui.QPixmap("images/space_down.png"))
        self.linkv40.setAlignment(QtCore.Qt.AlignCenter)
        self.linkv40.setObjectName("linkv40")
        self.boardLayout.addWidget(self.linkv40, 9, 0, 1, 1)
        self.linkv41 = QtWidgets.QLabel(self.centralwidget)
        self.linkv41.setPixmap(QtGui.QPixmap("images/space_down.png"))
        self.linkv41.setAlignment(QtCore.Qt.AlignCenter)
        self.linkv41.setObjectName("linkv41")
        self.boardLayout.addWidget(self.linkv41, 9, 2, 1, 1)
        self.linkv42 = QtWidgets.QLabel(self.centralwidget)
        self.linkv42.setPixmap(QtGui.QPixmap("images/space_down.png"))
        self.linkv42.setAlignment(QtCore.Qt.AlignCenter)
        self.linkv42.setObjectName("linkv42")
        self.boardLayout.addWidget(self.linkv42, 9, 4, 1, 1)
        self.linkv43 = QtWidgets.QLabel(self.centralwidget)
        self.linkv43.setPixmap(QtGui.QPixmap("images/space_down.png"))
        self.linkv43.setAlignment(QtCore.Qt.AlignCenter)
        self.linkv43.setObjectName("linkv43")
        self.boardLayout.addWidget(self.linkv43, 9, 6, 1, 1)
        self.linkv44 = QtWidgets.QLabel(self.centralwidget)
        self.linkv44.setPixmap(QtGui.QPixmap("images/space_down.png"))
        self.linkv44.setAlignment(QtCore.Qt.AlignCenter)
        self.linkv44.setObjectName("linkv44")
        self.boardLayout.addWidget(self.linkv44, 9, 8, 1, 1)
        self.linkv45 = QtWidgets.QLabel(self.centralwidget)
        self.linkv45.setPixmap(QtGui.QPixmap("images/space_down.png"))
        self.linkv45.setAlignment(QtCore.Qt.AlignCenter)
        self.linkv45.setObjectName("linkv45")
        self.boardLayout.addWidget(self.linkv45, 9, 10, 1, 1)
        
        self.linkx40 = QtWidgets.QLabel(self.centralwidget)
        self.linkx40.setPixmap(QtGui.QPixmap("images/space_cross.png"))
        self.linkx40.setObjectName("linkx40")
        self.boardLayout.addWidget(self.linkx40, 9, 1, 1, 1)
        self.linkx41 = QtWidgets.QLabel(self.centralwidget)
        self.linkx41.setPixmap(QtGui.QPixmap("images/space_cross.png"))
        self.linkx41.setObjectName("linkx41")
        self.boardLayout.addWidget(self.linkx41, 9, 3, 1, 1)
        self.linkx42 = QtWidgets.QLabel(self.centralwidget)
        self.linkx42.setPixmap(QtGui.QPixmap("images/space_cross.png"))
        self.linkx42.setObjectName("linkx42")
        self.boardLayout.addWidget(self.linkx42, 9, 5, 1, 1)
        self.linkx43 = QtWidgets.QLabel(self.centralwidget)
        self.linkx43.setPixmap(QtGui.QPixmap("images/space_cross.png"))
        self.linkx43.setObjectName("linkx43")
        self.boardLayout.addWidget(self.linkx43, 9, 7, 1, 1)
        self.linkx44 = QtWidgets.QLabel(self.centralwidget)
        self.linkx44.setPixmap(QtGui.QPixmap("images/space_cross.png"))
        self.linkx44.setObjectName("linkx44")
        self.boardLayout.addWidget(self.linkx44, 9, 9, 1, 1)
        
        #---------------------------------------------------
        
        self.letter50 = ImageLabel(self.centralwidget)
        self.letter50.setPosition(5, 0)
        self.letter50.setPixmap(QtGui.QPixmap("images/letter_Z.png"))
        self.letter50.setFont(letterFont)
        self.letter50.setMouseTracking(True)
        self.letter50.setScaledContents(True)
        self.letter50.setObjectName("letter50")
        self.boardLayout.addWidget(self.letter50, 10, 0, 1, 1)
        self.letter51 = ImageLabel(self.centralwidget)
        self.letter51.setPosition(5, 1)
        self.letter51.setPixmap(QtGui.QPixmap("images/letter_#.png"))
        self.letter51.setFont(letterFont)
        self.letter51.setMouseTracking(True)
        self.letter51.setScaledContents(True)
        self.letter51.setObjectName("letter51")
        self.boardLayout.addWidget(self.letter51, 10, 2, 1, 1)
        self.letter52 = ImageLabel(self.centralwidget)
        self.letter52.setPosition(5, 2)
        self.letter52.setPixmap(QtGui.QPixmap("images/letter_A.png"))
        self.letter52.setFont(letterFont)
        self.letter52.setMouseTracking(True)
        self.letter52.setScaledContents(True)
        self.letter52.setObjectName("letter52")
        self.boardLayout.addWidget(self.letter52, 10, 4, 1, 1)
        self.letter53 = ImageLabel(self.centralwidget)
        self.letter53.setPosition(5, 3)
        self.letter53.setPixmap(QtGui.QPixmap("images/letter_B.png"))
        self.letter53.setFont(letterFont)
        self.letter53.setMouseTracking(True)
        self.letter53.setScaledContents(True)
        self.letter53.setObjectName("letter53")
        self.boardLayout.addWidget(self.letter53, 10, 6, 1, 1)
        self.letter54 = ImageLabel(self.centralwidget)
        self.letter54.setPosition(5, 4)
        self.letter54.setPixmap(QtGui.QPixmap("images/letter_C.png"))
        self.letter54.setFont(letterFont)
        self.letter54.setMouseTracking(True)
        self.letter54.setScaledContents(True)
        self.letter54.setObjectName("letter54")
        self.boardLayout.addWidget(self.letter54, 10, 8, 1, 1)
        self.letter55 = ImageLabel(self.centralwidget)
        self.letter55.setPosition(5, 5)
        self.letter55.setPixmap(QtGui.QPixmap("images/letter_D.png"))
        self.letter55.setFont(letterFont)
        self.letter55.setMouseTracking(True)
        self.letter55.setScaledContents(True)
        self.letter55.setObjectName("letter55")
        self.boardLayout.addWidget(self.letter55, 10, 10, 1, 1)
        
        self.linkh50 = QtWidgets.QLabel(self.centralwidget)
        self.linkh50.setPixmap(QtGui.QPixmap("images/space_right.png"))
        self.linkh50.setObjectName("linkh50")
        self.boardLayout.addWidget(self.linkh50, 10, 1, 1, 1)
        self.linkh51 = QtWidgets.QLabel(self.centralwidget)
        self.linkh51.setPixmap(QtGui.QPixmap("images/space_right.png"))
        self.linkh51.setObjectName("linkh51")
        self.boardLayout.addWidget(self.linkh51, 10, 3, 1, 1)
        self.linkh52 = QtWidgets.QLabel(self.centralwidget)
        self.linkh52.setPixmap(QtGui.QPixmap("images/space_right.png"))
        self.linkh52.setObjectName("linkh52")
        self.boardLayout.addWidget(self.linkh52, 10, 5, 1, 1)
        self.linkh53 = QtWidgets.QLabel(self.centralwidget)
        self.linkh53.setPixmap(QtGui.QPixmap("images/space_right.png"))
        self.linkh53.setObjectName("linkh53")
        self.boardLayout.addWidget(self.linkh53, 10, 7, 1, 1)
        self.linkh54 = QtWidgets.QLabel(self.centralwidget)
        self.linkh54.setPixmap(QtGui.QPixmap("images/space_right.png"))
        self.linkh54.setObjectName("linkh54")
        self.boardLayout.addWidget(self.linkh54, 10, 9, 1, 1)
        
        self.gridLayoutMain.addLayout(self.boardLayout, 1, 0, 1, 1)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 883, 22))
        self.menubar.setNativeMenuBar(False)
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuBoggleBoard = QtWidgets.QMenu(self.menubar)
        self.menuBoggleBoard.setObjectName("menuBoggleBoard")
        self.menuDictionary = QtWidgets.QMenu(self.menubar)
        self.menuDictionary.setObjectName("menuDictionary")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")

        self.actionNew_4x4 = QtWidgets.QAction(MainWindow)
        self.actionNew_4x4.setObjectName("actionNew_4x4")
        self.actionClassic_4x4 = QtWidgets.QAction(MainWindow)
        self.actionClassic_4x4.setObjectName("actionClassic_4x4")
        self.actionDeluex_5x5 = QtWidgets.QAction(MainWindow)
        self.actionDeluex_5x5.setObjectName("actionDeluex_5x5")
        self.actionBig_5x5_1979 = QtWidgets.QAction(MainWindow)
        self.actionBig_5x5_1979.setObjectName("actionBig_5x5_1979")
        self.actionSuperBig_6x6 = QtWidgets.QAction(MainWindow)
        self.actionSuperBig_6x6.setObjectName("actionSuperBig_6x6")
        self.actionCustomBoard = QtWidgets.QAction(MainWindow)
        self.actionCustomBoard.setObjectName("actionCustomBoard")

        self.actionOSPD_US = QtWidgets.QAction(MainWindow)
        self.actionOSPD_US.setObjectName("actionOSPD_US")
        self.actionEOWL_UK = QtWidgets.QAction(MainWindow)
        self.actionEOWL_UK.setObjectName("actionEOWL_UK")
        self.actionSOWPODS = QtWidgets.QAction(MainWindow)
        self.actionSOWPODS.setObjectName("actionSOWPODS")
        self.actionCustomDictionary = QtWidgets.QAction(MainWindow)
        self.actionCustomDictionary.setObjectName("actionCustomDictionary")

        self.actionInstructions = QtWidgets.QAction(MainWindow)
        self.actionInstructions.setObjectName("actionInstructions")
        self.actionCheatSheet = QtWidgets.QAction(MainWindow)
        self.actionCheatSheet.setObjectName("actionCheatSheet")
        self.actionAboutAuthor = QtWidgets.QAction(MainWindow)
        self.actionAboutAuthor.setObjectName("actionAboutAuthor")
        
        self.menuFile.addAction(self.actionExit)
        self.menuBoggleBoard.addAction(self.actionNew_4x4)
        self.menuBoggleBoard.addAction(self.actionClassic_4x4)
        self.menuBoggleBoard.addAction(self.actionDeluex_5x5)
        self.menuBoggleBoard.addAction(self.actionBig_5x5_1979)
        self.menuBoggleBoard.addAction(self.actionSuperBig_6x6)
        self.menuBoggleBoard.addAction(self.actionCustomBoard)
        self.menuDictionary.addAction(self.actionOSPD_US)
        self.menuDictionary.addAction(self.actionEOWL_UK)
        self.menuDictionary.addAction(self.actionSOWPODS)
        self.menuDictionary.addAction(self.actionCustomDictionary)
        self.menuHelp.addAction(self.actionInstructions)
        self.menuHelp.addAction(self.actionCheatSheet)
        self.menuHelp.addAction(self.actionAboutAuthor)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuBoggleBoard.menuAction())
        self.menubar.addAction(self.menuDictionary.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.gameIntro.setText(_translate("MainWindow", "How to play:"))
        self.gameNew.setText(_translate("MainWindow", "New Game"))
        self.gameTime.setText(_translate("MainWindow", "Time"))
        self.gameScores.setText(_translate("MainWindow", "Scores:"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuBoggleBoard.setTitle(_translate("MainWindow", "Boggle Board"))
        self.menuDictionary.setTitle(_translate("MainWindow", "Dictionary"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionNew_4x4.setText(_translate("MainWindow", "4x4 New"))
        self.actionClassic_4x4.setText(_translate("MainWindow", "4x4 Classic"))
        self.actionDeluex_5x5.setText(_translate("MainWindow", "5x5 Deluxe"))
        self.actionBig_5x5_1979.setText(_translate("MainWindow", "5x5 Classic Big"))
        self.actionSuperBig_6x6.setText(_translate("MainWindow", "6x6 Super Big"))
        self.actionCustomBoard.setText(_translate("MainWindow", "Custom Board"))
        self.actionOSPD_US.setText(_translate("MainWindow", "Official Scrabble Players Dictionary (US)"))
        self.actionEOWL_UK.setText(_translate("MainWindow", "English Open Word List (UK)"))
        self.actionSOWPODS.setText(_translate("MainWindow", "SOWPODS (SCRABBLE) Dictionary"))
        self.actionCustomDictionary.setText(_translate("MainWindow", "User Select Dictionary File"))
        self.actionCheatSheet.setText(_translate("MainWindow", "View Cheat Sheet"))
        self.actionInstructions.setText(_translate("MainWindow", "Instructions"))
        self.actionAboutAuthor.setText(_translate("MainWindow", "About Author"))
        
