"""
" author Meisze Wong
"        www.linkedin.com/pub/macy-wong/46/550/37b/
"        github.com/mwong510ca/Boggle_TrieDataStructure
"""

# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'customBoggle.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, SubWindow):
        SubWindow.setObjectName("Enter your custom Boggle board")
        SubWindow.resize(500, 500)
        SubWindow.setMinimumSize(QtCore.QSize(500, 500))
        SubWindow.setMaximumSize(QtCore.QSize(500, 500))
        self.gridLayoutMain = QtWidgets.QGridLayout(SubWindow)
        self.gridLayoutMain.setObjectName("gridLayoutMain")
        
        self.sizeLayout = QtWidgets.QHBoxLayout()
        self.sizeLayout.setObjectName("sizeLayout")
        self.sizeLabel = QtWidgets.QLabel(SubWindow)
        self.sizeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.sizeLabel.setObjectName("sizeLabel")
        self.sizeLayout.addWidget(self.sizeLabel)

        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        
        self.sizeGroup = QtWidgets.QButtonGroup(SubWindow)
        self.sizeGroup.setObjectName("sizeGroup")        
        self.size4Button = QtWidgets.QRadioButton(SubWindow)
        self.size4Button.setSizePolicy(sizePolicy)
        self.size4Button.setMinimumSize(QtCore.QSize(50, 30))
        self.size4Button.setMaximumSize(QtCore.QSize(100, 30))
        self.size4Button.setObjectName("size4Button")
        self.sizeGroup.addButton(self.size4Button)
        self.sizeLayout.addWidget(self.size4Button)
        self.size5Button = QtWidgets.QRadioButton(SubWindow)
        self.size5Button.setSizePolicy(sizePolicy)
        self.size5Button.setMinimumSize(QtCore.QSize(50, 30))
        self.size5Button.setMaximumSize(QtCore.QSize(100, 30))
        self.size5Button.setObjectName("size5Button")
        self.sizeGroup.addButton(self.size5Button)
        self.sizeLayout.addWidget(self.size5Button)
        self.size6Button = QtWidgets.QRadioButton(SubWindow)
        self.size6Button.setSizePolicy(sizePolicy)
        self.size6Button.setMinimumSize(QtCore.QSize(50, 30))
        self.size6Button.setMaximumSize(QtCore.QSize(100, 30))
        self.size6Button.setObjectName("size6Button")
        self.sizeGroup.addButton(self.size6Button)
        self.sizeLayout.addWidget(self.size6Button)
        self.gridLayoutMain.addLayout(self.sizeLayout, 0, 0, 1, 1)
        
        self.submissionLayout = QtWidgets.QHBoxLayout()
        self.submissionLayout.setObjectName("submissionLayout")
        self.submitButton = QtWidgets.QPushButton(SubWindow)
        self.submitButton.setSizePolicy(sizePolicy)
        self.submitButton.setMinimumSize(QtCore.QSize(100, 30))
        self.submitButton.setMaximumSize(QtCore.QSize(200, 50))
        self.submitButton.setObjectName("submitButton")
        self.submissionLayout.addWidget(self.submitButton)
        self.cancelButton = QtWidgets.QPushButton(SubWindow)
        self.cancelButton.setSizePolicy(sizePolicy)
        self.cancelButton.setMinimumSize(QtCore.QSize(100, 30))
        self.cancelButton.setMaximumSize(QtCore.QSize(200, 50))
        self.cancelButton.setObjectName("cancelButton")
        self.submissionLayout.addWidget(self.cancelButton)
        self.gridLayoutMain.addLayout(self.submissionLayout, 2, 0, 1, 1)

        letterFont = QtGui.QFont()
        letterFont.setFamily("Superclarendon")
        letterFont.setPointSize(20) 

        self.setupLayout = QtWidgets.QGridLayout()
        self.setupLayout.setContentsMargins(0, 0, 0, 0)
        self.setupLayout.setObjectName("setupLayout")

        self.letter00 = QtWidgets.QComboBox(SubWindow)
        self.letter00.setFont(letterFont)
        self.letter00.setObjectName("letter00")
        self.setupLayout.addWidget(self.letter00, 1, 0, 1, 1)
        self.letter01 = QtWidgets.QComboBox(SubWindow)
        self.letter01.setFont(letterFont)
        self.letter01.setObjectName("letter01")
        self.setupLayout.addWidget(self.letter01, 1, 2, 1, 1)
        self.letter02 = QtWidgets.QComboBox(SubWindow)
        self.letter02.setFont(letterFont)
        self.letter02.setObjectName("letter02")
        self.setupLayout.addWidget(self.letter02, 1, 4, 1, 1)
        self.letter03 = QtWidgets.QComboBox(SubWindow)
        self.letter03.setFont(letterFont)
        self.letter03.setObjectName("letter03")
        self.setupLayout.addWidget(self.letter03, 1, 6, 1, 1)
        self.letter04 = QtWidgets.QComboBox(SubWindow)
        self.letter04.setFont(letterFont)
        self.letter04.setObjectName("letter04")
        self.setupLayout.addWidget(self.letter04, 1, 8, 1, 1)
        self.letter05 = QtWidgets.QComboBox(SubWindow)
        self.letter05.setFont(letterFont)
        self.letter05.setObjectName("letter05")
        self.setupLayout.addWidget(self.letter05, 1, 10, 1, 1)
        
        #---------------------------------------------------
        
        self.letter10 = QtWidgets.QComboBox(SubWindow)
        self.letter10.setFont(letterFont)
        self.letter10.setObjectName("letter10")
        self.setupLayout.addWidget(self.letter10, 3, 0, 1, 1)
        self.letter11 = QtWidgets.QComboBox(SubWindow)
        self.letter11.setFont(letterFont)
        self.letter11.setObjectName("letter11")
        self.setupLayout.addWidget(self.letter11, 3, 2, 1, 1)
        self.letter12 = QtWidgets.QComboBox(SubWindow)
        self.letter12.setFont(letterFont)
        self.letter12.setObjectName("letter12")
        self.setupLayout.addWidget(self.letter12, 3, 4, 1, 1)
        self.letter13 = QtWidgets.QComboBox(SubWindow)
        self.letter13.setFont(letterFont)
        self.letter13.setObjectName("letter13")
        self.setupLayout.addWidget(self.letter13, 3, 6, 1, 1)
        self.letter14 = QtWidgets.QComboBox(SubWindow)
        self.letter14.setFont(letterFont)
        self.letter14.setObjectName("letter14")
        self.setupLayout.addWidget(self.letter14, 3, 8, 1, 1)
        self.letter15 = QtWidgets.QComboBox(SubWindow)
        self.letter15.setFont(letterFont)
        self.letter15.setObjectName("letter15")
        self.setupLayout.addWidget(self.letter15, 3, 10, 1, 1)
        
        #---------------------------------------------------
        
        self.letter20 = QtWidgets.QComboBox(SubWindow)
        self.letter20.setFont(letterFont)
        self.letter20.setObjectName("letter20")
        self.setupLayout.addWidget(self.letter20, 5, 0, 1, 1)
        self.letter21 = QtWidgets.QComboBox(SubWindow)
        self.letter21.setFont(letterFont)
        self.letter21.setObjectName("letter21")
        self.setupLayout.addWidget(self.letter21, 5, 2, 1, 1)
        self.letter22 = QtWidgets.QComboBox(SubWindow)
        self.letter22.setFont(letterFont)
        self.letter22.setObjectName("letter22")
        self.setupLayout.addWidget(self.letter22, 5, 4, 1, 1)
        self.letter23 = QtWidgets.QComboBox(SubWindow)
        self.letter23.setFont(letterFont)
        self.letter23.setObjectName("letter23")
        self.setupLayout.addWidget(self.letter23, 5, 6, 1, 1)
        self.letter24 = QtWidgets.QComboBox(SubWindow)
        self.letter24.setFont(letterFont)
        self.letter24.setObjectName("letter24")
        self.setupLayout.addWidget(self.letter24, 5, 8, 1, 1)
        self.letter25 = QtWidgets.QComboBox(SubWindow)
        self.letter25.setFont(letterFont)
        self.letter25.setObjectName("letter25")
        self.setupLayout.addWidget(self.letter25, 5, 10, 1, 1)
        
        #---------------------------------------------------
        
        self.letter30 = QtWidgets.QComboBox(SubWindow)
        self.letter30.setFont(letterFont)
        self.letter30.setObjectName("letter30")
        self.setupLayout.addWidget(self.letter30, 7, 0, 1, 1)
        self.letter31 = QtWidgets.QComboBox(SubWindow)
        self.letter31.setFont(letterFont)
        self.letter31.setObjectName("letter31")
        self.setupLayout.addWidget(self.letter31, 7, 2, 1, 1)
        self.letter32 = QtWidgets.QComboBox(SubWindow)
        self.letter32.setFont(letterFont)
        self.letter32.setObjectName("letter32")
        self.setupLayout.addWidget(self.letter32, 7, 4, 1, 1)
        self.letter33 = QtWidgets.QComboBox(SubWindow)
        self.letter33.setFont(letterFont)
        self.letter33.setObjectName("letter33")
        self.setupLayout.addWidget(self.letter33, 7, 6, 1, 1)
        self.letter34 = QtWidgets.QComboBox(SubWindow)
        self.letter34.setFont(letterFont)
        self.letter34.setObjectName("letter34")
        self.setupLayout.addWidget(self.letter34, 7, 8, 1, 1)
        self.letter35 = QtWidgets.QComboBox(SubWindow)
        self.letter35.setFont(letterFont)
        self.letter35.setObjectName("letter35")
        self.setupLayout.addWidget(self.letter35, 7, 10, 1, 1)
        
        #---------------------------------------------------
        
        self.letter40 = QtWidgets.QComboBox(SubWindow)
        self.letter40.setFont(letterFont)
        self.letter40.setObjectName("letter40")
        self.setupLayout.addWidget(self.letter40, 9, 0, 1, 1)
        self.letter41 = QtWidgets.QComboBox(SubWindow)
        self.letter41.setFont(letterFont)
        self.letter41.setObjectName("letter41")
        self.setupLayout.addWidget(self.letter41, 9, 2, 1, 1)
        self.letter42 = QtWidgets.QComboBox(SubWindow)
        self.letter42.setFont(letterFont)
        self.letter42.setObjectName("letter42")
        self.setupLayout.addWidget(self.letter42, 9, 4, 1, 1)
        self.letter43 = QtWidgets.QComboBox(SubWindow)
        self.letter43.setFont(letterFont)
        self.letter43.setObjectName("letter43")
        self.setupLayout.addWidget(self.letter43, 9, 6, 1, 1)
        self.letter44 = QtWidgets.QComboBox(SubWindow)
        self.letter44.setFont(letterFont)
        self.letter44.setObjectName("letter44")
        self.setupLayout.addWidget(self.letter44, 9, 8, 1, 1)
        self.letter45 = QtWidgets.QComboBox(SubWindow)
        self.letter45.setFont(letterFont)
        self.letter45.setObjectName("letter45")
        self.setupLayout.addWidget(self.letter45, 9, 10, 1, 1)
        
        #---------------------------------------------------
        
        self.letter50 = QtWidgets.QComboBox(SubWindow)
        self.letter50.setFont(letterFont)
        self.letter50.setObjectName("letter50")
        self.setupLayout.addWidget(self.letter50, 11, 0, 1, 1)
        self.letter51 = QtWidgets.QComboBox(SubWindow)
        self.letter51.setFont(letterFont)
        self.letter51.setObjectName("letter51")
        self.setupLayout.addWidget(self.letter51, 11, 2, 1, 1)
        self.letter52 = QtWidgets.QComboBox(SubWindow)
        self.letter52.setFont(letterFont)
        self.letter52.setObjectName("letter52")
        self.setupLayout.addWidget(self.letter52, 11, 4, 1, 1)
        self.letter53 = QtWidgets.QComboBox(SubWindow)
        self.letter53.setFont(letterFont)
        self.letter53.setObjectName("letter53")
        self.setupLayout.addWidget(self.letter53, 11, 6, 1, 1)
        self.letter54 = QtWidgets.QComboBox(SubWindow)
        self.letter54.setFont(letterFont)
        self.letter54.setObjectName("letter54")
        self.setupLayout.addWidget(self.letter54, 11, 8, 1, 1)
        self.letter55 = QtWidgets.QComboBox(SubWindow)
        self.letter55.setFont(letterFont)
        self.letter55.setObjectName("letter55")
        self.setupLayout.addWidget(self.letter55, 11, 10, 1, 1)
        
        self.gridLayoutMain.addLayout(self.setupLayout, 1, 0, 1, 1)
        self.retranslateUi(SubWindow)
        QtCore.QMetaObject.connectSlotsByName(SubWindow)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Custom Boggle Board Setup"))
        self.sizeLabel.setText(_translate("Form", "Choose boggle size: "))
        self.size4Button.setText(_translate("Form", "4 x 4"))
        self.size5Button.setText(_translate("Form", "5 x 5"))
        self.size6Button.setText(_translate("Form", "6 x 6"))
        self.submitButton.setText(_translate("Form", "Submit"))
        self.cancelButton.setText(_translate("Form", "Cancel"))
        

